# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: centos:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Setup CF CLI
      - run: dnf install -y wget
      - run: wget -O /etc/yum.repos.d/cloudfoundry-cli.repo https://packages.cloudfoundry.org/fedora/cloudfoundry-cli.repo
      - run: dnf install -y cf-cli maven java-11-openjdk java-11-openjdk-devel java-11-openjdk-javadoc

      - run: mvn dependency:go-offline

      # run tests!
      - run: mvn verify site-deploy

      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: cf login -a https://api.run.pivotal.io -u $CF_USER -p "$CF_PASS" -o $CF_ORG -s $CF_SPACE
      - run: cf push -f manifest.yaml
